USE [master]
GO

/****** Object:  Database [DerafshSampleDB]    Script Date: 21/03/2018 08:24:01 PM ******/
CREATE DATABASE [DerafshSampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DerafshSampleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DerafshSampleDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DerafshSampleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DerafshSampleDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DerafshSampleDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DerafshSampleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DerafshSampleDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DerafshSampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DerafshSampleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DerafshSampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DerafshSampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET RECOVERY FULL 
GO

ALTER DATABASE [DerafshSampleDB] SET  MULTI_USER 
GO

ALTER DATABASE [DerafshSampleDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DerafshSampleDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DerafshSampleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DerafshSampleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DerafshSampleDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DerafshSampleDB] SET QUERY_STORE = OFF
GO

USE [DerafshSampleDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DerafshSampleDB] SET  READ_WRITE 
GO


------------------------------Tables-----------------------------------
USE [DerafshSampleDB]
GO

/****** Object:  Table [dbo].[Enum]    Script Date: 21/03/2018 08:35:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Enum](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EnumTypeId] [int] NOT NULL,	
	[Title] [nvarchar](100) NOT NULL,
	[Date] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Enums] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



CREATE TABLE [dbo].[EnumType](
	[Id] [int] IDENTITY(1,1) NOT NULL,	
	[Title] [nvarchar](100) NOT NULL,
	[Date] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_EnumTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO




CREATE TABLE [dbo].[Identity](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdentityEnumId] [int] NULL,
	[PersonId] [int] NULL,
	[OrganizationId] [int] NULL,
	[Date] [datetime] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_IDENTITY] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO



CREATE TABLE [dbo].[IdentityOrganization](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[RegistrationNumber] [nvarchar](50) NULL,
	[EconomicalNumber] [varchar](50) NULL,
	[NationalNumber] [varchar](11) NULL,
	[OrganizationStatusEnumId] [int] NOT NULL,
	[OrganizationEnumId] [int] NOT NULL,
	[RegistrationCityId] [int] NULL,
	[RegisterDate] [datetime] NULL,
 CONSTRAINT [PK_ORGANIZATION] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[IdentityPerson](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[GenderEnumId] [int] NOT NULL,
	[BirthDate] [datetime] NULL,
	[FatherName] [nvarchar](50) NULL,
	[NationalCode] [varchar](10) NULL,
	[BirthCityId] [int] NULL,
 CONSTRAINT [PK_PERSON] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[Address](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CityId] [int] NOT NULL,
	[FullAddress] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[PostalCode] [varchar](10) NULL,
	[IdentityId] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_ADDRESS] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


CREATE TABLE [dbo].[City](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NULL,	
	[CityCode] [varchar](5) NULL,
	[StateId] [int] NOT NULL,
	[Date] [datetime] NULL,
	[IsDeleted] [bit] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_CITY] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO



CREATE TABLE [dbo].[Country](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CountryCode] [varchar](10) NULL,
	[Name] [nvarchar](200) NULL,	
	[Date] [datetime] NULL,
	[IsDeleted] [bit] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_COUNTRY] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[Email](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MailAddress] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[IdentityId] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_EMAIL] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[Phone](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] [varchar](18) NOT NULL,
	[IdentityId] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_PHONE] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[State](
	[Id] [int] IDENTITY(1,1) NOT NULL,	
	[Name] [nvarchar](200) NULL,
	[CountryId] [int] NOT NULL,
	[Date] [datetime] NULL,
	[IsDeleted] [bit] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_STATE] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[State] ADD  CONSTRAINT [DF_State_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[State] ADD  CONSTRAINT [DF_State_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[State] ADD  CONSTRAINT [DF_State_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[State]  WITH CHECK ADD  CONSTRAINT [FK_STATE_COUNTRYID_COUNTRY] FOREIGN KEY([CountryId])
REFERENCES [dbo].[Country] ([Id])
GO

ALTER TABLE [dbo].[State] CHECK CONSTRAINT [FK_STATE_COUNTRYID_COUNTRY]
GO


ALTER TABLE [dbo].[Identity] ADD  CONSTRAINT [DF_Identity_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[Identity] ADD  CONSTRAINT [DF_Identity_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Identity] ADD  CONSTRAINT [DF_Identity_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Identity]  WITH CHECK ADD  CONSTRAINT [FK_Identity_Enum] FOREIGN KEY([Id])
REFERENCES [dbo].[Enum] ([Id])
GO

ALTER TABLE [dbo].[Identity] CHECK CONSTRAINT [FK_Identity_Enum]
GO

ALTER TABLE [dbo].[Identity]  WITH CHECK ADD  CONSTRAINT [FK_IDENTITY_ORGANIZAT_ORGANIZA] FOREIGN KEY([OrganizationId])
REFERENCES [dbo].[IdentityOrganization] ([Id])
GO

ALTER TABLE [dbo].[Identity] CHECK CONSTRAINT [FK_IDENTITY_ORGANIZAT_ORGANIZA]
GO

ALTER TABLE [dbo].[Identity]  WITH CHECK ADD  CONSTRAINT [FK_IDENTITY_PERSONALI_PERSON] FOREIGN KEY([PersonId])
REFERENCES [dbo].[IdentityPerson] ([Id])
GO

ALTER TABLE [dbo].[Identity] CHECK CONSTRAINT [FK_IDENTITY_PERSONALI_PERSON]
GO

ALTER TABLE [dbo].[Phone] ADD  CONSTRAINT [DF_Phone_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[Phone] ADD  CONSTRAINT [DF_Phone_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Phone] ADD  CONSTRAINT [DF_Phone_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Phone]  WITH CHECK ADD  CONSTRAINT [FK_PHONE_PHONEIDEN_IDENTITY] FOREIGN KEY([IdentityId])
REFERENCES [dbo].[Identity] ([Id])
GO

ALTER TABLE [dbo].[Phone] CHECK CONSTRAINT [FK_PHONE_PHONEIDEN_IDENTITY]
GO

ALTER TABLE [dbo].[Email] ADD  CONSTRAINT [DF_Email_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[Email] ADD  CONSTRAINT [DF_Email_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Email] ADD  CONSTRAINT [DF_Email_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Email]  WITH CHECK ADD  CONSTRAINT [FK_EMAIL_EMAILIDEN_IDENTITY] FOREIGN KEY([IdentityId])
REFERENCES [dbo].[Identity] ([Id])
GO

ALTER TABLE [dbo].[Email] CHECK CONSTRAINT [FK_EMAIL_EMAILIDEN_IDENTITY]
GO

ALTER TABLE [dbo].[Country] ADD  CONSTRAINT [DF_Country_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[Country] ADD  CONSTRAINT [DF_Country_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Country] ADD  CONSTRAINT [DF_Country_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO


ALTER TABLE [dbo].[IdentityPerson]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_BIRTHPLAC_CITY] FOREIGN KEY([BirthCityId])
REFERENCES [dbo].[City] ([Id])
GO

ALTER TABLE [dbo].[IdentityPerson] CHECK CONSTRAINT [FK_PERSON_BIRTHPLAC_CITY]
GO

ALTER TABLE [dbo].[IdentityPerson]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_GENDERID_GLOBALST] FOREIGN KEY([GenderEnumId])
REFERENCES [dbo].[Enum] ([Id])
GO

ALTER TABLE [dbo].[IdentityPerson] CHECK CONSTRAINT [FK_PERSON_GENDERID_GLOBALST]
GO


ALTER TABLE [dbo].[Address] ADD  CONSTRAINT [DF_Address_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[Address] ADD  CONSTRAINT [DF_Address_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Address] ADD  CONSTRAINT [DF_Address_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Address]  WITH CHECK ADD  CONSTRAINT [FK_Address_Identity] FOREIGN KEY([IdentityId])
REFERENCES [dbo].[Identity] ([Id])
GO

ALTER TABLE [dbo].[Address] CHECK CONSTRAINT [FK_Address_Identity]
GO

ALTER TABLE [dbo].[City] ADD  CONSTRAINT [DF_City_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[City] ADD  CONSTRAINT [DF_City_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[City] ADD  CONSTRAINT [DF_City_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[City]  WITH CHECK ADD  CONSTRAINT [FK_CITY_STATEID_STATE] FOREIGN KEY([StateId])
REFERENCES [dbo].[State] ([Id])
GO

ALTER TABLE [dbo].[City] CHECK CONSTRAINT [FK_CITY_STATEID_STATE]
GO

ALTER TABLE [dbo].[Enum] ADD  CONSTRAINT [DF_Enums_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[Enum] ADD  CONSTRAINT [DF_Enums_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Enum] ADD  CONSTRAINT [DF_Enums_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[Enum]  WITH CHECK ADD  CONSTRAINT [FK_Enums_EnumTypes] FOREIGN KEY([EnumTypeId])
REFERENCES [dbo].[EnumType] ([Id])
GO

ALTER TABLE [dbo].[Enum] CHECK CONSTRAINT [FK_Enums_EnumTypes]
GO

ALTER TABLE [dbo].[EnumType] ADD  CONSTRAINT [DF_EnumTypes_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[EnumType] ADD  CONSTRAINT [DF_EnumTypes_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[EnumType] ADD  CONSTRAINT [DF_EnumTypes_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

ALTER TABLE [dbo].[IdentityOrganization]  WITH CHECK ADD  CONSTRAINT [FK_IdentityOrganization_Enums] FOREIGN KEY([OrganizationEnumId])
REFERENCES [dbo].[Enum] ([Id])
GO

ALTER TABLE [dbo].[IdentityOrganization] CHECK CONSTRAINT [FK_IdentityOrganization_Enums]
GO

ALTER TABLE [dbo].[IdentityOrganization]  WITH CHECK ADD  CONSTRAINT [FK_ORGANIZA_CITYOFREG_CITY] FOREIGN KEY([RegistrationCityId])
REFERENCES [dbo].[City] ([Id])
GO

ALTER TABLE [dbo].[IdentityOrganization] CHECK CONSTRAINT [FK_ORGANIZA_CITYOFREG_CITY]
GO

ALTER TABLE [dbo].[IdentityOrganization]  WITH CHECK ADD  CONSTRAINT [FK_ORGANIZA_ORGANIZAT_GLOBALST] FOREIGN KEY([OrganizationStatusEnumId])
REFERENCES [dbo].[Enum] ([Id])
GO

ALTER TABLE [dbo].[IdentityOrganization] CHECK CONSTRAINT [FK_ORGANIZA_ORGANIZAT_GLOBALST]
GO

